[program:bts-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /root/apps/bts-guru-daemon/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/root/apps/bts-guru-daemon/worker.log
stopwaitsecs=3600
